# Generated by Django 3.2.10 on 2021-12-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
